//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baitaplon
{


    public partial class Dang_nhap
    {

        /// <summary>
        /// UCDang_nhap1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Baitaplon.USER_CONTROL.Dang_nhap UCDang_nhap1;
    }
}
